### ISSUE TITLE
find: -printf: unknown primary or operator | mac os x

### ISSUE THREAD

**Issue by Rezzakul** [alexppg/helmenv#5]
Thanks again for the tool but I found another issue

`helmenv list` throws an error:

`find: -printf: unknown primary or operator` 

I had to modify the command 

from:
` installed_versions="$(find "${HELM_BINARY_PATH}"/ -name '*helm-*' -printf '%f\n' | grep -Eo 'v([0-9]\.?)+$' | sed '/^$/d' | sort --version-sort)" `
to:
`installed_versions="$(find "${HELM_BINARY_PATH}"/ -name '*helm-*' -exec basename {} \; | grep -Eo 'v([0-9]\.?)+$' | sed '/^$/d' | sort --version-sort)"`

which should work on both mac and linux.

Again if you'd like I can do a pull request with my changes.

Thanks again for the tool

Cheers,
Rezzakul

**Comment by alexppg** [comment]
I'd very grateful if you could do that since I don't have a mac in which I can test your suggestion.

**Comment by darkn3rd** [comment]
Modified my `.zshrc` to use GNU find:

```
export PATH="$HOME/.bin:$PATH"
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
source $HOME/.helmenv/helmenv.sh
```

**Comment by alexppg** [comment]
Does that solve the issue? If it does and @Rezzakul can't do the change I suggest in the PR, I can add this to the readme.
Thanks!

**Comment by alexppg** [comment]
Closing since it's fixed.
