### ISSUE TITLE
helmenv list doesn't work on macOS

### ISSUE THREAD

**Issue by joaquinclearmetal** [alexppg/helmenv#7]
### Environment

```bash
uname -s
Darwin
```
### Steps
```bash
helmenv list
```

### Actual Results

```bash
find: -printf: unknown primary or operator
```

**Comment by alexppg** [comment]
Hi! I'm sorry, I can't test it in MacOS. Have you tried what's suggested here? https://github.com/alexppg/helmenv/issues/4

**Comment by alexppg** [comment]
Closing since the pointed issue is resolved.
